version: '3.9'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - doc-author-network

  postgres:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

    networks:
      - doc-author-network

networks:
  doc-author-network: