version: '3.9'


services:
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

    networks:
      - doc-author-network


#  rabbitmq:
#    container_name: rabbitmq
#    image: rabbitmq:3.8-management
#    command: rabbitmq-server
#    restart: unless-stopped
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - doc-author-network

networks:
  doc-author-network: